openapi: '3.1.0'
 
info: 
 title: Current Weather API
 
 description: Current Weather Data API from OpenWeather provides current weather details of a specified location. You can specify the location by providing its latitude and longitude. It provides weather of a specific location. And it accepts location as latitude and longitude.

 version: '1.0.1'
servers: 
  - url: https://api.openweathermap.org
paths: 
  /data/2.5/weather:
   get:
    description: Current Weather Data
    summary: get current weather
    tags: 
      - Weather
    parameters: 
      - name: lat
        in: query
        schema: 
          type: number
        required: true
      - name: lon
        in: query
        schema: 
          type: number
        required: true 
      - name: appid
        in: query
        schema: 
          type: string
        required: true 
    responses:
      "200":
       description: OK
       content: 
         application/json: 
           schema: 
            type: object
            properties: 
              coord:
                type: object
                properties: 
                  lat:
                    type: number
                  lon:
                    type: number
              base:
                type: string
              weather:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: number
                    main:
                      type: string
                    description:
                      type: string
                    icon: 
                      type: string
              main: 
                type: object
                properties:
                  temp: 
                    type: number
                  humidity:
                    type: number
                  feels_like: 
                    type: number 
                    
                  temp_min: 
                    type: number
                  temp_max: 
                    type: number
                  pressure: 
                    type: number
                  sea_level:
                    type: number
                  grnd_level:
                    type: number
              visibility: 
                type: number
              wind: 
                type: object
                properties:
                  speed:
                    type: number
                  deg: 
                    type: number
                  gust:
                    type: number
              clouds: 
                type: object
                properties:
                  all:
                   type: number
              dt:
                type: number
              sys:
                type: object
                properties:
                 country: 
                  type: string
                 sunrise: 
                    type: number
                 sunset:
                    type: number
              timezone:
                type: number
              id:
                type: number
              name:
                type: string
              cod:
                type: number                 

      "401":
       description: Invalid API Key
      "404":
       description: Location not found 
      "429":
       description: Rate Limit Exceeded
      "500":
       description: Internal Server Error   

security: 
  - ApiKeyAuth: []
        
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: appid
        
        
           



  

    
     


     

      




  
  





    
  
    
